---
server:
    install: '1'
    packages: [imagemagick, npm, unzip]
    timezone: Europe/Berlin
    locale: de_DE.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: xenial64, hostname: default, ip: 192.160.14.15, memory: '512', sharedfolder: ./, useVagrantCloud: '0', syncType: '0' }
apache:
    install: '1'
    docroot: /vagrant/
    servername: content.fly
mysql:
    install: '1'
    root_password: ''
    database: db
    user: user
    password: pass
    dump: ''
    ppa: mysql-5.6
php:
    install: '1'
    upload_max_size: '20M'
    max_execution_time: 240
    memory_limit: '256M'
    ppa: php
    packages: [php7.1-fpm, php7.1-cli, php7.1-common, php7.1-mbstring, php7.1-gd, php7.1-intl, php7.1-xml, php7.1-mysql, php7.1-mcrypt, php7.1-zip]
xdebug:
    install: '1'
composer:
    install: '1'

